language: python
python:
  - 3.5
  - 3.6
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libnetcdf-dev
install:
    - pip install -r requirements.txt -r test_requirements.txt
    - pip install .
script:
    - pytest
    - flake8 bcweather/
